import { ToolItem } from "@/types/tool";

export const TOOLS: Record<string, ToolItem> = {
  "percentage-calculator": {
    id: "percentage-calculator",
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    category: "calculators",
    shortDescription: "Calculate percentages, find what percentage a number is of another, or determine percentage change.",
    description: "Free online percentage calculator with step-by-step mathematical breakdowns, worked examples, and multi-mode calculations.",
    title: "Percentage Calculator – Fast & Accurate Online Tool",
    metaDescription: "Calculate percentages easily: find X% of Y, what percent X is of Y, or percentage increase/decrease. Includes instant steps and formulas.",
    keywords: ["percentage calculator", "calculate percentage", "percent of a number", "percentage formula", "how to calculate percentage"],
    synonyms: ["percent calc", "percentage tool", "percent finder"],
    iconName: "Percent",
    status: "published",
    seoPriority: 98,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Math Team", role: "Applied Mathematics Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      latex: "P = \\frac{X}{100} \\times Y",
      text: "Percentage Amount = (Percentage / 100) × Total Value",
      explanation: "To find a percentage of a number, convert the percentage into a decimal by dividing by 100, then multiply by the total number.",
    },
    howItWorks: [
      "Select your calculation mode (e.g. Find X% of Y, or What % is X of Y).",
      "Enter the numeric values into the designated input fields.",
      "The exact result, fractional equivalent, and step-by-step arithmetic appear instantly.",
      "Copy or share the final calculation with one click.",
    ],
    workedExamples: [
      {
        title: "Calculating 20% of $150",
        scenario: "You want to find how much a 20% tip or discount is on a $150 bill.",
        inputs: { Percentage: 20, Total: 150 },
        steps: ["Divide 20 by 100: 20 / 100 = 0.20", "Multiply 0.20 by 150: 0.20 × 150 = 30"],
        result: "30 (or $30.00)",
      },
      {
        title: "Finding what percentage 45 is of 180",
        scenario: "You scored 45 out of 180 on a practice quiz.",
        inputs: { Part: 45, Total: 180 },
        steps: ["Divide 45 by 180: 45 / 180 = 0.25", "Multiply by 100: 0.25 × 100 = 25%"],
        result: "25%",
      },
    ],
    useCases: [
      "Retail shopping discounts and clearance sales",
      "Calculating restaurant tips and bill splits",
      "Academic test grades and score percentages",
      "Business profit margins and tax calculations",
    ],
    faq: [
      {
        question: "How do I calculate a percentage of a number manually?",
        answer: "Convert the percentage to a decimal by dividing it by 100, then multiply that decimal by the number you want to find the percentage of. For example, 15% of 200 is 0.15 × 200 = 30.",
      },
      {
        question: "What is the difference between percentage and percentage points?",
        answer: "A percentage is a relative proportion out of 100, whereas a percentage point is the simple arithmetic difference between two percentages. For instance, if an interest rate goes from 4% to 5%, it increased by 1 percentage point, which is a 25% relative increase.",
      },
      {
        question: "Can percentages be greater than 100%?",
        answer: "Yes. Percentages greater than 100% represent quantities that exceed the baseline whole. For example, 150% of 20 is 30.",
      },
    ],
    relatedToolSlugs: [
      "percentage-increase-calculator",
      "percentage-decrease-calculator",
      "discount-calculator",
      "ratio-calculator",
    ],
  },

  "percentage-increase-calculator": {
    id: "percentage-increase-calculator",
    slug: "percentage-increase-calculator",
    name: "Percentage Increase Calculator",
    category: "calculators",
    shortDescription: "Calculate the percentage increase from an initial value to a final value, or add a percentage to a base amount.",
    description: "Determine the exact percentage rise and absolute monetary or unit increase between any two values with step-by-step formulas.",
    title: "Percentage Increase Calculator – Calculate Growth & Rises",
    metaDescription: "Calculate the percentage increase between two numbers or add a percentage to a base number. Free, fast, and transparent math.",
    keywords: ["percentage increase calculator", "percent increase", "calculate percentage increase", "growth rate calculator", "percent change"],
    iconName: "TrendingUp",
    status: "published",
    seoPriority: 94,
    isPopular: true,
    author: { name: "NexusTools Math Team", role: "Applied Mathematics Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-12",
    formula: {
      latex: "\\text{Percentage Increase} = \\frac{\\text{New} - \\text{Old}}{|\\text{Old}|} \\times 100",
      text: "Percentage Increase = ((New Value - Original Value) / Original Value) × 100",
      explanation: "Subtract the starting value from the new value, divide that difference by the starting value, and multiply by 100.",
    },
    howItWorks: [
      "Input your original baseline value.",
      "Input the new increased value (or the percentage you wish to add).",
      "Review the percentage change and the absolute difference.",
    ],
    workedExamples: [
      {
        title: "Salary increase from $50,000 to $65,000",
        scenario: "Calculate the percentage raise when moving to a new job.",
        inputs: { "Original Salary": 50000, "New Salary": 65000 },
        steps: ["Difference: 65,000 - 50,000 = 15,000", "Divide by baseline: 15,000 / 50,000 = 0.30", "Multiply by 100: 0.30 × 100 = 30%"],
        result: "+30.00% increase (+$15,000)",
      },
    ],
    useCases: [
      "Measuring annual salary and compensation raises",
      "Tracking business revenue and user growth metrics",
      "Analyzing inflation and price hikes over time",
    ],
    faq: [
      {
        question: "How do you calculate a 15% increase on a number?",
        answer: "Multiply the base number by 1.15. For example, a 15% increase on $100 is $100 × 1.15 = $115.",
      },
    ],
    relatedToolSlugs: [
      "percentage-calculator",
      "percentage-decrease-calculator",
      "discount-calculator",
    ],
  },

  "percentage-decrease-calculator": {
    id: "percentage-decrease-calculator",
    slug: "percentage-decrease-calculator",
    name: "Percentage Decrease Calculator",
    category: "calculators",
    shortDescription: "Calculate the percentage drop between two values or subtract a percentage from a number.",
    description: "Accurately compute percentage decreases, price drops, weight loss percentages, and depreciation.",
    title: "Percentage Decrease Calculator – Calculate Reductions & Drops",
    metaDescription: "Calculate percentage decrease and markdown percentages instantly. Step-by-step formulas and clear explanations.",
    keywords: ["percentage decrease calculator", "percent decrease", "calculate percentage reduction", "markdown calculator"],
    iconName: "TrendingDown",
    status: "published",
    seoPriority: 92,
    author: { name: "NexusTools Math Team", role: "Applied Mathematics Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-12",
    formula: {
      latex: "\\text{Percentage Decrease} = \\frac{\\text{Old} - \\text{New}}{\\text{Old}} \\times 100",
      text: "Percentage Decrease = ((Original Value - New Value) / Original Value) × 100",
      explanation: "Subtract the new value from the starting value, divide by the starting value, and multiply by 100.",
    },
    howItWorks: [
      "Enter the initial starting value.",
      "Enter the final decreased value.",
      "The tool calculates the reduction percentage and absolute difference immediately.",
    ],
    workedExamples: [
      {
        title: "Product price reduction from $80 to $60",
        scenario: "Find the percentage discount when a store lowers an item price.",
        inputs: { "Original Price": 80, "New Price": 60 },
        steps: ["Difference: 80 - 60 = 20", "Divide by starting value: 20 / 80 = 0.25", "Multiply by 100: 0.25 × 100 = 25%"],
        result: "-25.00% decrease (-$20.00)",
      },
    ],
    useCases: [
      "Calculating clearance markdowns and sale price drops",
      "Tracking body weight loss percentages",
      "Evaluating asset depreciation",
    ],
    faq: [
      {
        question: "Can a percentage decrease exceed 100%?",
        answer: "In physical or financial contexts starting from zero or above, a decrease to zero is a 100% decrease. Decreases larger than 100% occur only when values drop into negative territory.",
      },
    ],
    relatedToolSlugs: [
      "percentage-calculator",
      "percentage-increase-calculator",
      "discount-calculator",
    ],
  },

  "discount-calculator": {
    id: "discount-calculator",
    slug: "discount-calculator",
    name: "Discount Calculator",
    category: "calculators",
    shortDescription: "Calculate sale prices, total savings, and stacked double discounts.",
    description: "Determine the final price after single or combined percentage discounts with tax considerations.",
    title: "Discount Calculator – Calculate Sale Price & Savings",
    metaDescription: "Calculate final sale price and total money saved with single and stacked discounts. Fast, simple, and mobile friendly.",
    keywords: ["discount calculator", "sale price calculator", "calculate discount", "coupon calculator", "savings calculator"],
    iconName: "Tag",
    status: "published",
    seoPriority: 95,
    isPopular: true,
    author: { name: "NexusTools Math Team", role: "Applied Mathematics Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-10",
    formula: {
      latex: "\\text{Final Price} = \\text{Original Price} \\times \\left(1 - \\frac{\\text{Discount}\\%}{100}\\right)",
      text: "Final Price = Original Price × (1 - (Discount % / 100))",
      explanation: "Multiply the original price by the complement of the discount percentage.",
    },
    howItWorks: [
      "Enter the original item retail price.",
      "Enter the primary discount percentage (e.g. 25%).",
      "Optionally enter an additional stacked coupon percentage (e.g. extra 10% off).",
      "View your exact final checkout price and total dollars saved.",
    ],
    workedExamples: [
      {
        title: "$120 jacket with 30% off plus 10% extra coupon",
        scenario: "Applying an extra coupon code on top of an existing store sale.",
        inputs: { "Original Price": 120, "Primary Discount": 30, "Extra Discount": 10 },
        steps: [
          "First discount: $120 - 30% ($36) = $84",
          "Second discount: $84 - 10% ($8.40) = $75.60",
          "Total savings: $120 - $75.60 = $44.40 (37% effective discount)",
        ],
        result: "$75.60 final price ($44.40 saved)",
      },
    ],
    useCases: [
      "Black Friday and holiday shopping price verification",
      "Stacking membership and promo coupons",
      "Estimating wholesale and trade discounts",
    ],
    faq: [
      {
        question: "Why is 20% off plus an extra 20% off not 40% off?",
        answer: "Because the second 20% is applied to the already discounted price, not the original price. For a $100 item, 20% off leaves $80, and 20% off $80 is $16, resulting in a $64 final price (a 36% total discount).",
      },
    ],
    relatedToolSlugs: [
      "percentage-calculator",
      "percentage-decrease-calculator",
    ],
  },

  "average-calculator": {
    id: "average-calculator",
    slug: "average-calculator",
    name: "Average Calculator",
    category: "calculators",
    shortDescription: "Calculate the mean, median, mode, range, standard deviation, and sum for any set of numbers.",
    description: "Statistical average calculator providing mean, median, mode, range, and variance from comma-separated or space-separated lists.",
    title: "Average Calculator – Mean, Median, Mode & Range",
    metaDescription: "Calculate statistical mean, median, mode, range, sum, count, and standard deviation for any set of numbers online.",
    keywords: ["average calculator", "calculate mean", "median calculator", "mode calculator", "standard deviation calculator"],
    iconName: "BarChart2",
    status: "published",
    seoPriority: 90,
    author: { name: "NexusTools Math Team", role: "Applied Mathematics Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      latex: "\\bar{x} = \\frac{\\sum_{i=1}^{n} x_i}{n}",
      text: "Mean = Sum of all values / Total number of values",
      explanation: "Add all input values together and divide by the total count of values.",
    },
    howItWorks: [
      "Paste or type your numbers separated by commas, spaces, or line breaks.",
      "The tool instantly parses the inputs and sorts the dataset.",
      "View mean (average), median (middle value), mode (most frequent), min, max, range, and standard deviation.",
    ],
    workedExamples: [
      {
        title: "Exam scores: 85, 90, 75, 90, 100",
        scenario: "Find the central tendencies of 5 test scores.",
        inputs: { Dataset: "85, 90, 75, 90, 100" },
        steps: [
          "Sum: 85 + 90 + 75 + 90 + 100 = 440",
          "Count: 5",
          "Mean: 440 / 5 = 88",
          "Sorted: 75, 85, 90, 90, 100 -> Median is 90",
          "Mode: 90 (appears twice)",
        ],
        result: "Mean = 88 | Median = 90 | Mode = 90",
      },
    ],
    useCases: [
      "Student grade point averages and classroom metrics",
      "Analyzing user survey ratings and response data",
      "Sales performance and average ticket size calculations",
    ],
    faq: [
      {
        question: "When should I use median instead of mean?",
        answer: "Use median when your dataset contains extreme outliers or is skewed (such as household income or real estate prices), as the median is not distorted by extreme high or low numbers.",
      },
    ],
    relatedToolSlugs: [
      "percentage-calculator",
      "ratio-calculator",
    ],
  },

  "ratio-calculator": {
    id: "ratio-calculator",
    slug: "ratio-calculator",
    name: "Ratio Calculator",
    category: "calculators",
    shortDescription: "Simplify ratios, find equivalent proportions, and solve for unknown variables in A:B = C:D.",
    description: "Comprehensive ratio simplifier and proportion solver with step-by-step reduction using greatest common divisors.",
    title: "Ratio Calculator – Simplify Ratios & Solve Proportions",
    metaDescription: "Simplify ratios into lowest terms or solve proportions (A:B = C:D). Step-by-step arithmetic and decimal equivalents.",
    keywords: ["ratio calculator", "simplify ratio", "proportion calculator", "solve ratio", "aspect ratio calculator"],
    iconName: "Sliders",
    status: "published",
    seoPriority: 88,
    author: { name: "NexusTools Math Team", role: "Applied Mathematics Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-08",
    formula: {
      latex: "\\frac{A}{B} = \\frac{C}{D} \\implies A \\cdot D = B \\cdot C",
      text: "Cross Multiplication: A × D = B × C",
      explanation: "In any true proportion, the product of the extremes equals the product of the means.",
    },
    howItWorks: [
      "To simplify: enter the antecedent (A) and consequent (B) to get lowest common terms.",
      "To solve: enter 3 known values in A:B = C:D and leave 1 value blank to solve for the unknown.",
    ],
    workedExamples: [
      {
        title: "Simplifying 1920 : 1080 (Screen Resolution)",
        scenario: "Find the aspect ratio of 1080p full HD.",
        inputs: { "Value A": 1920, "Value B": 1080 },
        steps: ["Find GCD of 1920 and 1080 = 120", "1920 / 120 = 16", "1080 / 120 = 9"],
        result: "16 : 9",
      },
    ],
    useCases: [
      "Screen aspect ratio and image resizing calculations",
      "Culinary recipe scaling and ingredient proportions",
      "Architectural scale drawings and model building",
    ],
    faq: [
      {
        question: "How do you simplify a ratio with decimals?",
        answer: "Multiply both terms by 10, 100, or whatever power of 10 eliminates the decimal point, then divide both numbers by their Greatest Common Divisor (GCD).",
      },
    ],
    relatedToolSlugs: [
      "percentage-calculator",
      "average-calculator",
    ],
  },

  "simple-interest-calculator": {
    id: "simple-interest-calculator",
    slug: "simple-interest-calculator",
    name: "Simple Interest Calculator",
    category: "finance",
    shortDescription: "Calculate simple interest on loans or savings with annual balance breakdown.",
    description: "Determine exact simple interest earned or owed using I = P × r × t with complete year-by-year amortization preview.",
    title: "Simple Interest Calculator – Fast & Transparent Math",
    metaDescription: "Calculate simple interest on investments or loans using I = Prt. Includes full annual breakdowns and mathematical formulas.",
    keywords: ["simple interest calculator", "calculate simple interest", "interest formula", "I=Prt calculator", "loan interest"],
    iconName: "Percent",
    status: "published",
    seoPriority: 89,
    author: { name: "NexusTools Finance Team", role: "Financial Modeling Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      latex: "I = P \\times r \\times t",
      text: "Interest (I) = Principal (P) × Annual Interest Rate (r) × Time in Years (t)",
      explanation: "Simple interest is calculated solely on the original principal amount, without compounding prior interest.",
    },
    howItWorks: [
      "Enter your starting principal balance.",
      "Enter the annual interest rate as a percentage.",
      "Specify the duration in years.",
      "View total interest accrued, ending balance, and the annual accumulation schedule.",
    ],
    workedExamples: [
      {
        title: "$10,000 at 5% annual interest for 3 years",
        scenario: "Calculating return on a simple fixed-term note.",
        inputs: { Principal: 10000, "Rate (%)": 5, "Years": 3 },
        steps: ["Interest = 10,000 × 0.05 × 3 = $1,500", "Total Balance = 10,000 + 1,500 = $11,500"],
        result: "$1,500 interest ($11,500 total)",
      },
    ],
    useCases: [
      "Short-term promissory notes and personal loans",
      "Auto loans with non-compounding terms",
      "Basic educational financial modeling",
    ],
    faq: [
      {
        question: "What is the difference between simple and compound interest?",
        answer: "Simple interest is calculated only on the initial principal amount. Compound interest is calculated on both the initial principal and the accumulated interest from previous periods.",
      },
    ],
    relatedToolSlugs: [
      "compound-interest-calculator",
      "loan-calculator",
    ],
  },

  "compound-interest-calculator": {
    id: "compound-interest-calculator",
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    category: "finance",
    shortDescription: "Calculate compound investment growth with regular monthly deposits and compounding frequencies.",
    description: "Accurately project long-term investment growth, total principal contributed, and interest earned over time.",
    title: "Compound Interest Calculator – Investment & Savings Growth",
    metaDescription: "Calculate compound interest with monthly deposits, multiple compounding frequencies, and detailed growth breakdown.",
    keywords: ["compound interest calculator", "investment calculator", "savings growth calculator", "compound growth", "interest rate calculator"],
    iconName: "TrendingUp",
    status: "published",
    seoPriority: 97,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Finance Team", role: "Financial Modeling Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      latex: "A = P \\left(1 + \\frac{r}{n}\\right)^{nt}",
      text: "A = P(1 + r/n)^(nt) + PMT × [((1 + r/n)^(nt) - 1) / (r/n)]",
      explanation: "Calculates future balance based on principal, compounding periods per year, and recurring annuity deposits.",
    },
    howItWorks: [
      "Enter your initial starting principal deposit.",
      "Enter an optional monthly recurring contribution.",
      "Set your expected annual return rate and investment horizon in years.",
      "Select your compounding frequency (Monthly, Annually, etc.).",
      "Examine your projected total portfolio balance, total interest, and year-by-year table.",
    ],
    workedExamples: [
      {
        title: "$5,000 starting + $200/mo at 8% for 10 years",
        scenario: "Retirement savings accumulation plan.",
        inputs: { "Initial Deposit": 5000, "Monthly Deposit": 200, "Interest Rate": 8, "Years": 10 },
        steps: [
          "Total principal deposited: $5,000 + ($200 × 120) = $29,000",
          "Compounded growth over 120 periods at 8% annual return",
        ],
        result: "$47,404.14 final balance ($18,404.14 interest earned)",
      },
    ],
    useCases: [
      "Retirement portfolio projection (401k, IRA, Index Funds)",
      "High-yield savings account (HYSA) growth forecasting",
      "College tuition and long-term wealth planning",
    ],
    faq: [
      {
        question: "How often should interest compound?",
        answer: "Most savings accounts compound daily and credit monthly. Standard investment funds compound continuously with market dividends and reinvestments.",
      },
      {
        question: "What is the Rule of 72?",
        answer: "The Rule of 72 is a quick mental math shortcut: divide 72 by your annual interest rate to estimate how many years it will take to double your money. At 8% interest, 72 / 8 = 9 years.",
      },
    ],
    relatedToolSlugs: [
      "simple-interest-calculator",
      "loan-calculator",
      "percentage-calculator",
    ],
  },

  "loan-calculator": {
    id: "loan-calculator",
    slug: "loan-calculator",
    name: "Loan & Mortgage Calculator",
    category: "finance",
    shortDescription: "Calculate monthly loan payments, total interest costs, and full amortization schedules.",
    description: "Determine exact monthly installments for auto loans, personal loans, and mortgages with detailed principal vs interest breakdowns.",
    title: "Loan Calculator – Calculate Monthly Payment & Amortization",
    metaDescription: "Calculate monthly loan payments, total interest paid, and complete amortization schedule for mortgages, auto, or personal loans.",
    keywords: ["loan calculator", "mortgage calculator", "monthly payment calculator", "amortization calculator", "car loan calculator"],
    iconName: "CreditCard",
    status: "published",
    seoPriority: 96,
    isPopular: true,
    author: { name: "NexusTools Finance Team", role: "Financial Modeling Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      latex: "M = P \\frac{r(1+r)^n}{(1+r)^n - 1}",
      text: "Monthly Payment = P × [ r(1+r)^n / ((1+r)^n - 1) ]",
      explanation: "Standard fixed-rate loan payment formula where P is principal, r is monthly interest rate, and n is total payment periods.",
    },
    howItWorks: [
      "Enter total loan amount requested.",
      "Enter the annual interest rate (APR).",
      "Enter loan term in years (e.g. 5 for auto, 30 for mortgage).",
      "View your fixed monthly payment, total lifetime interest, and monthly payoff schedule.",
    ],
    workedExamples: [
      {
        title: "$250,000 Mortgage at 6.5% for 30 Years",
        scenario: "Evaluating a residential fixed-rate home loan.",
        inputs: { "Loan Amount": 250000, "Interest Rate (%)": 6.5, "Term (Years)": 30 },
        steps: [
          "Monthly rate r = 0.065 / 12 = 0.005417",
          "Total payments n = 30 × 12 = 360",
          "Apply standard amortization formula",
        ],
        result: "$1,580.17 / month ($318,861.20 total interest)",
      },
    ],
    useCases: [
      "Home mortgage financing comparisons",
      "Car loan and vehicle financing affordability checks",
      "Debt consolidation and personal loan budgeting",
    ],
    faq: [
      {
        question: "How does making extra payments affect my loan?",
        answer: "Extra payments go directly toward reducing the principal balance, which drastically reduces the total lifetime interest paid and shortens the loan payoff date.",
      },
    ],
    relatedToolSlugs: [
      "compound-interest-calculator",
      "simple-interest-calculator",
    ],
  },

  "length-converter": {
    id: "length-converter",
    slug: "length-converter",
    name: "Length Converter",
    category: "converters",
    shortDescription: "Convert between meters, feet, inches, centimeters, kilometers, miles, and yards.",
    description: "Instant bidirectional unit converter for metric and imperial distance measurements with high mathematical precision.",
    title: "Length Converter – Metric & Imperial Distance Conversion",
    metaDescription: "Convert length and distance: meters, feet, inches, centimeters, kilometers, miles, yards. Real-time conversion formula.",
    keywords: ["length converter", "meters to feet", "cm to inches", "inches to cm", "miles to km", "feet to meters"],
    iconName: "Ruler",
    status: "published",
    seoPriority: 93,
    isPopular: true,
    author: { name: "NexusTools Engineering Team", role: "Measurement Standards Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-10",
    formula: {
      text: "Target Value = (Input Value × Input Factor to Base) / Target Factor to Base",
      explanation: "Normalizes the input length into standard SI meters, then transforms to the destination unit.",
    },
    howItWorks: [
      "Select your starting length unit and target unit.",
      "Type the numerical value.",
      "The result and exact conversion constant update instantaneously.",
    ],
    workedExamples: [
      {
        title: "Converting 100 Centimeters to Inches",
        scenario: "Measuring furniture dimensions across unit systems.",
        inputs: { Value: 100, From: "Centimeters (cm)", To: "Inches (in)" },
        steps: ["1 inch = 2.54 cm", "100 / 2.54 = 39.370078..."],
        result: "39.3701 inches",
      },
    ],
    useCases: [
      "International construction and DIY measurements",
      "Travel distances and navigation",
      "Height and clothing sizing charts",
    ],
    faq: [
      {
        question: "How many inches are in a meter?",
        answer: "There are approximately 39.3701 inches in 1 meter (1 meter = 100 cm / 2.54 cm/inch).",
      },
    ],
    relatedToolSlugs: [
      "weight-converter",
      "temperature-converter",
      "data-storage-converter",
    ],
  },

  "weight-converter": {
    id: "weight-converter",
    slug: "weight-converter",
    name: "Weight & Mass Converter",
    category: "converters",
    shortDescription: "Convert between kilograms, pounds, grams, ounces, stones, and metric tons.",
    description: "Convert imperial and metric mass units with verified international standards (e.g. 1 lb = 0.45359237 kg).",
    title: "Weight Converter – Kilograms, Pounds, Ounces, Grams",
    metaDescription: "Convert weight and mass units instantly: kg to lbs, lbs to kg, grams to ounces, and stones. Clean, precise conversion formulas.",
    keywords: ["weight converter", "kg to lbs", "lbs to kg", "grams to ounces", "ounces to grams", "mass converter"],
    iconName: "Scale",
    status: "published",
    seoPriority: 93,
    isPopular: true,
    author: { name: "NexusTools Engineering Team", role: "Measurement Standards Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-10",
    formula: {
      text: "Target Mass = (Input Mass × Input Factor in kg) / Target Factor in kg",
      explanation: "Converts the given mass into international standard kilograms, then scales to the target unit.",
    },
    howItWorks: [
      "Select your source mass unit and target unit.",
      "Enter any positive number.",
      "View instant result and conversion formula.",
    ],
    workedExamples: [
      {
        title: "Converting 70 Kilograms to Pounds",
        scenario: "Converting human body weight.",
        inputs: { Value: 70, From: "Kilograms (kg)", To: "Pounds (lb)" },
        steps: ["1 kg ≈ 2.20462262 lb", "70 × 2.20462262 = 154.3235..."],
        result: "154.3236 lbs",
      },
    ],
    useCases: [
      "Fitness tracking and body weight conversions",
      "Culinary recipe ingredient weight scaling",
      "Air cargo and luggage weight compliance",
    ],
    faq: [
      {
        question: "How many pounds are in 1 kilogram?",
        answer: "1 kilogram is exactly equal to approximately 2.20462 pounds.",
      },
    ],
    relatedToolSlugs: [
      "length-converter",
      "temperature-converter",
      "data-storage-converter",
    ],
  },

  "temperature-converter": {
    id: "temperature-converter",
    slug: "temperature-converter",
    name: "Temperature Converter",
    category: "converters",
    shortDescription: "Convert between Celsius (°C), Fahrenheit (°F), and Kelvin (K).",
    description: "Accurate thermodynamic temperature conversion engine with absolute zero validation.",
    title: "Temperature Converter – Celsius, Fahrenheit & Kelvin",
    metaDescription: "Convert temperatures between Celsius, Fahrenheit, and Kelvin instantly. Complete conversion formulas and absolute zero checks.",
    keywords: ["temperature converter", "celsius to fahrenheit", "fahrenheit to celsius", "c to f", "f to c", "kelvin converter"],
    iconName: "Thermometer",
    status: "published",
    seoPriority: 91,
    isPopular: true,
    author: { name: "NexusTools Engineering Team", role: "Measurement Standards Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-10",
    formula: {
      latex: "^{\\circ}\\text{F} = (^{\\circ}\\text{C} \\times 9/5) + 32",
      text: "Fahrenheit = (Celsius × 9/5) + 32 | Celsius = (Fahrenheit - 32) × 5/9 | Kelvin = Celsius + 273.15",
      explanation: "Standard thermodynamic linear scale transformations.",
    },
    howItWorks: [
      "Select your source temperature scale and target scale.",
      "Enter temperature value.",
      "The converted temperature appears instantly.",
    ],
    workedExamples: [
      {
        title: "Converting 100°C (Boiling point) to Fahrenheit",
        scenario: "Water boiling temperature at sea level.",
        inputs: { Value: 100, From: "Celsius (°C)", To: "Fahrenheit (°F)" },
        steps: ["(100 × 9/5) + 32 = 180 + 32 = 212"],
        result: "212°F",
      },
    ],
    useCases: [
      "Baking and oven cooking temperature conversions",
      "International weather forecasts and travel planning",
      "Scientific lab experiments and physics problems",
    ],
    faq: [
      {
        question: "At what temperature are Celsius and Fahrenheit equal?",
        answer: "-40° Celsius is exactly equal to -40° Fahrenheit.",
      },
    ],
    relatedToolSlugs: [
      "length-converter",
      "weight-converter",
      "data-storage-converter",
    ],
  },

  "data-storage-converter": {
    id: "data-storage-converter",
    slug: "data-storage-converter",
    name: "Data Storage Converter",
    category: "converters",
    shortDescription: "Convert between Bytes, KB, MB, GB, TB, and PB in binary (1024) or decimal (1000) formats.",
    description: "Convert digital storage capacity and file sizes with binary (1024) and decimal (1000) storage toggles.",
    title: "Data Storage Converter – Bytes, KB, MB, GB, TB & PB",
    metaDescription: "Convert digital file sizes and memory: Bytes, Kilobytes, Megabytes, Gigabytes, Terabytes. Supports binary 1024 and decimal 1000.",
    keywords: ["data storage converter", "mb to gb", "gb to mb", "bytes to mb", "tb to gb", "file size converter"],
    iconName: "HardDrive",
    status: "published",
    seoPriority: 89,
    author: { name: "NexusTools Engineering Team", role: "Software Engineering Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-12",
    formula: {
      text: "Binary: 1 KB = 1,024 Bytes | Decimal: 1 KB = 1,000 Bytes",
      explanation: "Computers calculate memory in powers of 2 (1024 bytes per KiB), while drive manufacturers advertise in powers of 10 (1000 bytes per KB).",
    },
    howItWorks: [
      "Choose binary (1024) or metric decimal (1000) conversion base.",
      "Enter your starting file size and units.",
      "Review the full conversion breakdown across all digital units.",
    ],
    workedExamples: [
      {
        title: "Converting 4096 MB to Gigabytes",
        scenario: "Computer RAM calculation.",
        inputs: { Value: 4096, From: "MB", To: "GB" },
        steps: ["In binary base 1024: 4096 / 1024 = 4"],
        result: "4.0 GB (or 4.0 GiB)",
      },
    ],
    useCases: [
      "Hard drive and SSD real formatted capacity verification",
      "Cloud storage quota and file upload planning",
      "Network bandwidth download time estimations",
    ],
    faq: [
      {
        question: "Why does my 1TB hard drive only show 931 GB in Windows?",
        answer: "Hard drive manufacturers market 1 TB as 1,000,000,000,000 bytes (decimal base 1000). Operating systems like Windows report capacity in binary gigabytes (Gibibytes, where 1 GiB = 1024³ bytes). 1,000,000,000,000 / 1024³ ≈ 931.32 GiB.",
      },
    ],
    relatedToolSlugs: [
      "length-converter",
      "subnet-calculator",
    ],
  },

  "age-calculator": {
    id: "age-calculator",
    slug: "age-calculator",
    name: "Age Calculator",
    category: "date-time",
    shortDescription: "Calculate exact chronological age in years, months, days, hours, and minutes, plus countdown to next birthday.",
    description: "High-precision age calculator accounting for leap years, variable calendar month lengths, and weekday born.",
    title: "Age Calculator – Calculate Exact Age & Next Birthday",
    metaDescription: "Find your exact age in years, months, weeks, days, hours, and minutes. Includes birthday countdown and day of the week born.",
    keywords: ["age calculator", "calculate age", "how old am i", "chronological age calculator", "birthday calculator"],
    iconName: "Calendar",
    status: "published",
    seoPriority: 99,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Editorial Team", role: "Timekeeping Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      text: "Age = Target Date - Date of Birth (accounting for leap years and exact month boundaries)",
      explanation: "Calculates years elapsed, remaining months adjusted by calendar days, and total accumulated days and hours.",
    },
    howItWorks: [
      "Select your date of birth.",
      "Optionally select a target calculation date (defaults to today).",
      "View exact age broken down by years, months, and days, plus total accumulated hours, minutes, and next birthday countdown.",
    ],
    workedExamples: [
      {
        title: "Born March 15, 1995 evaluated on March 15, 2025",
        scenario: "Milestone 30th birthday evaluation.",
        inputs: { "Birth Date": "1995-03-15", "Current Date": "2025-03-15" },
        steps: ["2025 - 1995 = 30 full years", "Months: 0, Days: 0", "Total Days: 10,958 days (including 7 leap year extra days)"],
        result: "30 years 0 months 0 days",
      },
    ],
    useCases: [
      "Official document verification and eligibility checks",
      "Next milestone birthday countdowns and celebrations",
      "Infant and toddler development age in exact weeks/months",
    ],
    faq: [
      {
        question: "Does this age calculator account for leap years?",
        answer: "Yes. The algorithm dynamically accounts for every leap year (366 days) between the start date and the end date.",
      },
    ],
    relatedToolSlugs: [
      "date-difference-calculator",
      "days-between-dates",
      "unix-timestamp-converter",
    ],
  },

  "date-difference-calculator": {
    id: "date-difference-calculator",
    slug: "date-difference-calculator",
    name: "Date Difference & Duration Calculator",
    category: "date-time",
    shortDescription: "Calculate the exact duration between two dates in days, business days, weeks, and months.",
    description: "Determine the number of days, weekend days, and working business days between any two calendar dates.",
    title: "Date Difference Calculator – Days, Weeks & Business Days",
    metaDescription: "Calculate days between two dates, working business days, weekend count, weeks, and months. Fast and accurate calendar math.",
    keywords: ["date difference calculator", "days between dates", "business days calculator", "calculate date duration", "calendar difference"],
    iconName: "CalendarRange",
    status: "published",
    seoPriority: 92,
    isPopular: true,
    author: { name: "NexusTools Editorial Team", role: "Timekeeping Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "Total Days = (End Date in ms - Start Date in ms) / 86,400,000",
      explanation: "Iterates through calendar days to count business days (Monday-Friday) and weekend days (Saturday-Sunday).",
    },
    howItWorks: [
      "Pick your start date and end date.",
      "Toggle whether to include the end date in the total count.",
      "Review the total calendar days, working business days, weekends, and week/month breakdown.",
    ],
    workedExamples: [
      {
        title: "Duration from June 1, 2026 to August 31, 2026",
        scenario: "Summer project timeline estimation.",
        inputs: { "Start Date": "2026-06-01", "End Date": "2026-08-31" },
        steps: ["Total days: 91 days", "Business days (Mon-Fri): 66 days", "Weekend days: 25 days"],
        result: "91 total days (66 working days)",
      },
    ],
    useCases: [
      "Contract deadline and milestone scheduling",
      "Event and vacation countdowns",
      "Legal statutory notice and business day calculations",
    ],
    faq: [
      {
        question: "What days are considered business days?",
        answer: "Standard business days are Monday through Friday, excluding Saturdays and Sundays.",
      },
    ],
    relatedToolSlugs: [
      "age-calculator",
      "days-between-dates",
      "unix-timestamp-converter",
    ],
  },

  "days-between-dates": {
    id: "days-between-dates",
    slug: "days-between-dates",
    name: "Days Between Dates Calculator",
    category: "date-time",
    shortDescription: "Quickly find the exact number of days between two dates.",
    description: "Simplified calendar tool to find total day count and week counts between any two dates with a clean, fast interface.",
    title: "Days Between Dates – Count Days Easily Online",
    metaDescription: "Calculate the exact number of days and weeks between any two dates. Clean, fast, and 100% accurate calendar calculator.",
    keywords: ["days between dates", "day counter", "how many days between", "calculate days", "date span counter"],
    iconName: "CalendarDays",
    status: "published",
    seoPriority: 91,
    author: { name: "NexusTools Editorial Team", role: "Timekeeping Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "Days = Math.floor((End - Start) / 86400000)",
      explanation: "Computes total elapsed milliseconds divided by milliseconds in a solar day (24 × 60 × 60 × 1000).",
    },
    howItWorks: [
      "Select your start and end dates.",
      "Instantly see the exact day count, weeks, and percentage of the year.",
    ],
    workedExamples: [
      {
        title: "January 1 to December 31 in a standard year",
        scenario: "Full calendar year span.",
        inputs: { "Start Date": "2025-01-01", "End Date": "2025-12-31" },
        steps: ["Total days: 364 days (365 if including end day)"],
        result: "364 days (52 weeks)",
      },
    ],
    useCases: [
      "Subscription renewal tracking",
      "Pregnancy and milestone day counting",
      "Billing cycles and rent intervals",
    ],
    faq: [
      {
        question: "Does this include leap days?",
        answer: "Yes, all standard UTC calendar leap days are automatically included.",
      },
    ],
    relatedToolSlugs: [
      "date-difference-calculator",
      "age-calculator",
    ],
  },

  "unix-timestamp-converter": {
    id: "unix-timestamp-converter",
    slug: "unix-timestamp-converter",
    name: "Unix Timestamp Converter",
    category: "date-time",
    shortDescription: "Convert Unix epoch timestamps to human-readable dates (UTC and local) and vice versa.",
    description: "Developer utility to convert seconds and milliseconds timestamps into ISO 8601, RFC 2822, and localized date strings.",
    title: "Unix Timestamp Converter – Epoch to Date & Date to Epoch",
    metaDescription: "Convert Unix timestamps to human readable dates (ISO 8601, UTC, local time) and convert dates to epoch timestamps instantly.",
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to timestamp", "epoch time"],
    iconName: "Clock",
    status: "published",
    seoPriority: 94,
    isPopular: true,
    author: { name: "NexusTools Engineering Team", role: "Software Engineering Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      text: "Unix Timestamp = Seconds elapsed since January 1, 1970 00:00:00 UTC",
      explanation: "Standard POSIX time representation.",
    },
    howItWorks: [
      "Type or paste any 10-digit (seconds) or 13-digit (milliseconds) Unix timestamp, or pick a date from the calendar.",
      "The tool decodes the timestamp into UTC, ISO 8601, RFC 2822, and your browser's local timezone.",
      "Copy formatted timestamps with a single click.",
    ],
    workedExamples: [
      {
        title: "Decoding Timestamp 1700000000",
        scenario: "Inspecting API payload timestamp.",
        inputs: { Timestamp: 1700000000 },
        steps: ["1,700,000,000 seconds since 1970-01-01T00:00:00Z"],
        result: "2023-11-14T22:13:20.000Z (UTC)",
      },
    ],
    useCases: [
      "Debugging database records and API tokens (JWTs)",
      "Log file inspection and server timestamp alignment",
      "Scheduling cron jobs and event triggers",
    ],
    faq: [
      {
        question: "What is the Year 2038 problem (Y2K38)?",
        answer: "On January 19, 2038 at 03:14:07 UTC, 32-bit signed integer timestamps will overflow into negative values. Modern 64-bit systems are immune to this issue.",
      },
    ],
    relatedToolSlugs: [
      "timezone-converter",
      "date-difference-calculator",
      "base64-encoder-decoder",
    ],
  },

  "timezone-converter": {
    id: "timezone-converter",
    slug: "timezone-converter",
    name: "Time Zone Converter & World Clock",
    category: "date-time",
    shortDescription: "Convert dates and times across global timezones with daylight saving time (DST) awareness.",
    description: "Compare world meeting times and convert hours across New York (EST), London (GMT/BST), Tokyo (JST), and more.",
    title: "Time Zone Converter – Convert World Clock Times Easily",
    metaDescription: "Convert time across major global timezones. Accurate DST handling, meeting planner, and world clock reference.",
    keywords: ["timezone converter", "world clock", "convert timezones", "time difference", "est to gmt", "pst to utc"],
    iconName: "Globe",
    status: "published",
    seoPriority: 90,
    author: { name: "NexusTools Engineering Team", role: "Timekeeping Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-12",
    formula: {
      text: "Target Time = UTC Time + Target IANA Timezone Offset",
      explanation: "Converts local time to universal coordinated time (UTC), then applies the specific destination offset including seasonal DST.",
    },
    howItWorks: [
      "Select your source timezone and input a date and time.",
      "Select your target destination timezone.",
      "View the converted time, day difference (if crossed midnight), and current UTC offset.",
    ],
    workedExamples: [
      {
        title: "9:00 AM New York (EDT, UTC-4) to London (BST, UTC+1)",
        scenario: "International team sync scheduling.",
        inputs: { "Source Time": "09:00 AM EDT", "Target Zone": "Europe/London (BST)" },
        steps: ["9:00 AM EDT is 13:00 UTC", "13:00 UTC + 1 hour BST = 14:00 (2:00 PM) BST"],
        result: "2:00 PM (14:00) London Time (+5 hours difference)",
      },
    ],
    useCases: [
      "Scheduling international team meetings and webinars",
      "Booking flights and coordinating global travel",
      "Tracking global market trading opening hours",
    ],
    faq: [
      {
        question: "Does this tool automatically account for Daylight Saving Time (DST)?",
        answer: "Yes, standard IANA timezones dynamically calculate whether Daylight Saving Time is active on the selected date.",
      },
    ],
    relatedToolSlugs: [
      "unix-timestamp-converter",
      "date-difference-calculator",
    ],
  },

  "ip-address-checker": {
    id: "ip-address-checker",
    slug: "ip-address-checker",
    name: "IP Address Checker & Inspector",
    category: "technology",
    shortDescription: "Inspect IPv4/IPv6 addresses, determine IP class, private/public status, and binary format.",
    description: "Analyze network IP addresses, validate IPv4 formats, check subnet boundaries, and inspect private RFC 1918 ranges.",
    title: "IP Address Checker – Inspect IPv4/IPv6 & Network Range",
    metaDescription: "Check and inspect IP addresses: validate format, identify private vs public ranges, class categorization, and binary notation.",
    keywords: ["ip address checker", "check ip", "ipv4 inspector", "private ip lookup", "what is my ip"],
    iconName: "Network",
    status: "published",
    seoPriority: 91,
    isPopular: true,
    author: { name: "NexusTools Networking Team", role: "Network Infrastructure Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "IPv4 = 4 octets (32 bits) in dotted-decimal format (X.X.X.X, where 0 <= X <= 255)",
      explanation: "Validates format structure and assigns RFC classes (A, B, C, D, E) and private address spaces.",
    },
    howItWorks: [
      "Enter any IPv4 address (e.g. 192.168.1.1 or 8.8.8.8).",
      "Inspect the IP class, public/private classification, hexadecimal format, and 32-bit binary representation.",
    ],
    workedExamples: [
      {
        title: "Analyzing 192.168.1.100",
        scenario: "Local home router network analysis.",
        inputs: { IP: "192.168.1.100" },
        steps: ["Check octets: 192, 168, 1, 100", "Recognize RFC 1918 Private Range (192.168.0.0/16)", "Class: Class C"],
        result: "Private Local IP (Class C)",
      },
    ],
    useCases: [
      "Home and enterprise router configuration",
      "Firewall rule verification and IP classification",
      "Network troubleshooting and diagnostics",
    ],
    faq: [
      {
        question: "What are the private IPv4 address ranges?",
        answer: "Class A: 10.0.0.0 to 10.255.255.255, Class B: 172.16.0.0 to 172.31.255.255, Class C: 192.168.0.0 to 192.168.255.255, and Loopback: 127.0.0.1.",
      },
    ],
    relatedToolSlugs: [
      "subnet-calculator",
      "cidr-calculator",
    ],
  },

  "subnet-calculator": {
    id: "subnet-calculator",
    slug: "subnet-calculator",
    name: "Subnet Calculator & IPv4 Subnetting",
    category: "technology",
    shortDescription: "Calculate network addresses, broadcast addresses, subnet masks, wildcard masks, and usable host ranges.",
    description: "Complete IPv4 subnetting engine for network engineers, sysadmins, and students studying for CCNA/Network+ certifications.",
    title: "Subnet Calculator – IPv4 Network, Broadcast & Host Range",
    metaDescription: "Calculate IPv4 subnet mask, network address, broadcast address, wildcard mask, and usable host IP ranges online.",
    keywords: ["subnet calculator", "ipv4 subnet calculator", "network calculator", "broadcast address calculator", "subnet mask calculator"],
    iconName: "Binary",
    status: "published",
    seoPriority: 98,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Networking Team", role: "Network Infrastructure Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      latex: "\\text{Usable Hosts} = 2^{32 - \\text{CIDR}} - 2",
      text: "Network Address = IP & Subnet Mask | Broadcast Address = Network | Wildcard Mask",
      explanation: "Performs bitwise AND and OR operations across 32-bit integers to deduce network boundaries and host allocations.",
    },
    howItWorks: [
      "Enter your base IPv4 address (e.g. 192.168.1.50).",
      "Select your CIDR prefix (e.g. /24) or dotted-decimal subnet mask.",
      "Instantly review the network address, first and last usable host IPs, broadcast address, and binary bit masks.",
    ],
    workedExamples: [
      {
        title: "Subnetting 10.0.5.23 with a /24 mask",
        scenario: "Standard departmental subnet allocation.",
        inputs: { IP: "10.0.5.23", CIDR: 24 },
        steps: [
          "Subnet Mask: 255.255.255.0",
          "Network Address: 10.0.5.0",
          "First Usable Host: 10.0.5.1",
          "Last Usable Host: 10.0.5.254",
          "Broadcast Address: 10.0.5.255",
          "Total Usable Hosts: 254",
        ],
        result: "Network: 10.0.5.0/24 (254 Usable Hosts)",
      },
    ],
    useCases: [
      "Cloud VPC subnet provisioning (AWS, Azure, GCP)",
      "Enterprise LAN segmentation and VLAN routing",
      "Cisco CCNA, CCNP, and CompTIA Network+ exam prep",
    ],
    faq: [
      {
        question: "Why do we subtract 2 from total subnet hosts?",
        answer: "Because the very first address in a subnet is reserved as the Network Identifier, and the last address is reserved as the Subnet Broadcast address. The remaining addresses in between are usable for host devices.",
      },
    ],
    relatedToolSlugs: [
      "cidr-calculator",
      "ip-address-checker",
    ],
  },

  "cidr-calculator": {
    id: "cidr-calculator",
    slug: "cidr-calculator",
    name: "CIDR Calculator (Classless Inter-Domain Routing)",
    category: "technology",
    shortDescription: "Calculate CIDR notation prefixes (/0 to /32), subnet masks, wildcard masks, and host counts.",
    description: "Convert between CIDR prefix notation and dotted-decimal subnet masks with complete address pool metrics.",
    title: "CIDR Calculator – Prefix Notation to Subnet Mask & Hosts",
    metaDescription: "Convert CIDR slash notation (/24, /16, etc.) to subnet mask, wildcard mask, and available IP count. Fast and accurate.",
    keywords: ["cidr calculator", "cidr to subnet mask", "cidr notation", "slash notation", "ip range calculator"],
    iconName: "Cpu",
    status: "published",
    seoPriority: 93,
    isPopular: true,
    author: { name: "NexusTools Networking Team", role: "Network Infrastructure Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "Subnet Mask Bits = CIDR Prefix length of 1s followed by (32 - CIDR) 0s",
      explanation: "Translates CIDR prefix notation directly into 32-bit contiguous binary subnet masks.",
    },
    howItWorks: [
      "Select or type any CIDR prefix (e.g. /16, /22, /28).",
      "Inspect the corresponding dotted subnet mask, wildcard mask, total IP capacity, and usable host count.",
    ],
    workedExamples: [
      {
        title: "Evaluating a /28 CIDR block",
        scenario: "Small server rack subnet allocation.",
        inputs: { CIDR: 28 },
        steps: ["28 bits of 1s = 255.255.255.240", "Remaining host bits: 32 - 28 = 4 bits", "Total IPs = 2⁴ = 16", "Usable hosts = 16 - 2 = 14"],
        result: "Mask: 255.255.255.240 | 14 Usable Hosts",
      },
    ],
    useCases: [
      "AWS / GCP VPC route table configuration",
      "Firewall access control list (ACL) definition",
      "ISP IP block allocation",
    ],
    faq: [
      {
        question: "What is CIDR notation?",
        answer: "CIDR (Classless Inter-Domain Routing) notation is a compact representation of an IP address and its associated routing prefix, expressed as a slash followed by the count of leading network bits (e.g. 192.168.0.0/24).",
      },
    ],
    relatedToolSlugs: [
      "subnet-calculator",
      "ip-address-checker",
    ],
  },

  "json-formatter": {
    id: "json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter, Validator & Minifier",
    category: "technology",
    shortDescription: "Format, validate, beautify, and minify JSON payloads with line-by-line syntax error detection.",
    description: "Client-side JSON beautifier and syntax validator with custom indentation (2 or 4 spaces), tree view, and minification.",
    title: "JSON Formatter – Beautify, Validate & Minify JSON Online",
    metaDescription: "Format, beautify, validate, and minify JSON strings with instant syntax error highlighting. 100% private client-side processing.",
    keywords: ["json formatter", "json beautifier", "json validator", "minify json", "format json online"],
    iconName: "Code",
    status: "published",
    seoPriority: 97,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Engineering Team", role: "Software Engineering Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      text: "JSON.stringify(JSON.parse(input), null, indentSpaces)",
      explanation: "Parses JSON AST in memory, validates RFC 8259 conformity, and reformats with custom whitespace.",
    },
    howItWorks: [
      "Paste your raw or minified JSON text into the editor.",
      "Click 'Format' to beautify with 2 or 4 spaces, or 'Minify' to strip all whitespace.",
      "If the JSON contains syntax errors, view the exact line and character location.",
      "Copy formatted JSON to clipboard with one click.",
    ],
    workedExamples: [
      {
        title: "Formatting minified API response",
        scenario: "Cleaning up a compacted REST response.",
        inputs: { JSON: '{"status":"ok","code":200,"data":{"id":42,"name":"Nexus"}}' },
        steps: ["Parse AST", "Apply 2-space indentation", "Pretty print object keys"],
        result: "Clean indented JSON structure",
      },
    ],
    useCases: [
      "API payload debugging and inspection",
      "Cleaning config files (package.json, tsconfig.json)",
      "Minifying JSON for production asset payload reduction",
    ],
    faq: [
      {
        question: "Is my JSON data sent to your server?",
        answer: "No. All JSON parsing, formatting, and validation happens 100% locally inside your web browser. No data ever leaves your computer.",
      },
    ],
    relatedToolSlugs: [
      "base64-encoder-decoder",
      "uuid-generator",
      "url-encoder-decoder",
    ],
  },

  "base64-encoder-decoder": {
    id: "base64-encoder-decoder",
    slug: "base64-encoder-decoder",
    name: "Base64 Encoder & Decoder",
    category: "technology",
    shortDescription: "Encode text to Base64 or decode Base64 strings with UTF-8 support and URL-safe mode.",
    description: "Fast, secure client-side Base64 conversion tool supporting international UTF-8 characters and RFC 4648 URL-safe formatting.",
    title: "Base64 Encoder & Decoder – Convert Text & Base64 Online",
    metaDescription: "Encode text to Base64 or decode Base64 strings instantly with full UTF-8 unicode and URL-safe support. 100% private.",
    keywords: ["base64 encoder", "base64 decoder", "encode base64", "decode base64", "base64 converter"],
    iconName: "FileCode",
    status: "published",
    seoPriority: 96,
    isPopular: true,
    author: { name: "NexusTools Engineering Team", role: "Software Engineering Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      text: "Base64 encodes 3 bytes (24 bits) into 4 characters (6 bits each) from a 64-character ASCII alphabet",
      explanation: "Converts binary or UTF-8 text into a safe ASCII string representation suitable for transmission over text protocols.",
    },
    howItWorks: [
      "Select 'Encode' or 'Decode' mode.",
      "Type or paste your text into the input field.",
      "Toggle URL-Safe format (- and _ instead of + and /) if embedding in query parameters.",
      "Copy the result instantly.",
    ],
    workedExamples: [
      {
        title: "Encoding 'Hello World!' to Base64",
        scenario: "Basic authorization or data string encoding.",
        inputs: { Text: "Hello World!" },
        steps: ["Convert UTF-8 characters to bytes", "Group into 6-bit chunks", "Map to Base64 ASCII alphabet"],
        result: "SGVsbG8gV29ybGQh",
      },
    ],
    useCases: [
      "Encoding HTTP Basic Auth credentials",
      "Embedding data URIs in CSS and HTML",
      "Decoding webhook signatures and API tokens",
    ],
    faq: [
      {
        question: "Is Base64 an encryption method?",
        answer: "No. Base64 is an encoding scheme designed for data transport, not encryption. Anyone can decode a Base64 string without a password.",
      },
    ],
    relatedToolSlugs: [
      "url-encoder-decoder",
      "json-formatter",
      "hash-generator",
    ],
  },

  "url-encoder-decoder": {
    id: "url-encoder-decoder",
    slug: "url-encoder-decoder",
    name: "URL Encoder & Decoder (Percent Encoding)",
    category: "technology",
    shortDescription: "Encode and decode URLs and URI query parameters into percent-encoded ASCII format.",
    description: "Safely encode special characters, spaces, and non-ASCII symbols for query strings and REST endpoints.",
    title: "URL Encoder & Decoder – Percent-Encoding Online Tool",
    metaDescription: "Encode and decode URL parameters (percent-encoding) online. Handles spaces, query params, UTF-8 strings, and special characters.",
    keywords: ["url encoder", "url decoder", "percent encoding", "encode uri", "decode uri component"],
    iconName: "Link",
    status: "published",
    seoPriority: 91,
    author: { name: "NexusTools Engineering Team", role: "Software Engineering Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-12",
    formula: {
      text: "Unsafe characters are replaced with '%' followed by their two-digit hexadecimal ASCII/UTF-8 byte value",
      explanation: "Converts reserved and non-ASCII characters into compliant RFC 3986 format.",
    },
    howItWorks: [
      "Enter your raw URL or encoded string.",
      "Select 'Encode' (converts special characters to %XX) or 'Decode' (restores human-readable text).",
      "Copy the converted string with one click.",
    ],
    workedExamples: [
      {
        title: "Encoding query string: 'search query=hello world & test'",
        scenario: "Sanitizing search parameters.",
        inputs: { Text: "search query=hello world & test" },
        steps: ["Space becomes %20", "& becomes %26", "= becomes %3D"],
        result: "search%20query%3Dhello%20world%20%26%20test",
      },
    ],
    useCases: [
      "Constructing safe REST API query parameters",
      "Fixing broken web URLs with special characters",
      "Decoding complex tracking UTM parameters",
    ],
    faq: [
      {
        question: "What is the difference between encodeURI and encodeURIComponent?",
        answer: "encodeURI preserves URL structural delimiters like http://, /, and ?, whereas encodeURIComponent encodes all special characters, making it suitable for query string parameters.",
      },
    ],
    relatedToolSlugs: [
      "base64-encoder-decoder",
      "slug-generator",
    ],
  },

  "uuid-generator": {
    id: "uuid-generator",
    slug: "uuid-generator",
    name: "UUID v4 Generator (Bulk & Custom)",
    category: "technology",
    shortDescription: "Generate cryptographically secure version 4 UUIDs (Universally Unique Identifiers) in bulk.",
    description: "Generate random, collision-resistant UUID v4 strings with uppercase/lowercase toggles and hyphens removal.",
    title: "UUID Generator – Cryptographically Secure UUID v4",
    metaDescription: "Generate random UUID v4 identifiers in bulk. Cryptographically secure, zero server tracking, with uppercase and hyphen options.",
    keywords: ["uuid generator", "uuid v4", "guid generator", "random uuid", "bulk uuid generator"],
    iconName: "Key",
    status: "published",
    seoPriority: 95,
    isPopular: true,
    author: { name: "NexusTools Engineering Team", role: "Software Engineering Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "UUID v4 = 128-bit number in 8-4-4-4-12 hex format with version 4 and RFC 4122 variant bits",
      explanation: "Uses window.crypto.randomUUID() / crypto.getRandomValues() for true cryptographic entropy.",
    },
    howItWorks: [
      "Select the quantity of UUIDs to generate (1 to 50).",
      "Customize formatting: uppercase/lowercase, hyphens on/off.",
      "Click 'Generate' to create new IDs and copy with one click.",
    ],
    workedExamples: [
      {
        title: "Standard UUID v4 output",
        scenario: "Primary database record key generation.",
        inputs: { Quantity: 1, Format: "Standard" },
        steps: ["Generate 128 pseudo-random bits", "Set version 4 (0100) and variant (10xx)", "Format with 4 hyphens"],
        result: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
      },
    ],
    useCases: [
      "Database primary keys and distributed unique IDs",
      "API request correlation and session tracking tokens",
      "Software testing mock data generation",
    ],
    faq: [
      {
        question: "Can two UUID v4 values ever collide?",
        answer: "The probability of generating a duplicate UUID v4 is so astronomically low (1 in 2^122) that it is virtually zero across billions of generated keys.",
      },
    ],
    relatedToolSlugs: [
      "password-generator",
      "hash-generator",
      "json-formatter",
    ],
  },

  "password-generator": {
    id: "password-generator",
    slug: "password-generator",
    name: "Password Generator & Entropy Meter",
    category: "technology",
    shortDescription: "Generate cryptographically secure, uncrackable random passwords with entropy strength estimation.",
    description: "Generate highly secure random passwords with customizable lengths, symbols, numbers, and lookalike character exclusion.",
    title: "Password Generator – Secure Random Passwords & Entropy",
    metaDescription: "Generate strong, secure passwords with customizable length, symbols, numbers, and entropy calculation. 100% private client-side tool.",
    keywords: ["password generator", "secure password generator", "random password", "password entropy", "strong password generator"],
    iconName: "Shield",
    status: "published",
    seoPriority: 98,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Security Team", role: "Cybersecurity Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      latex: "E = L \\times \\log_2(R)",
      text: "Entropy (bits) = Password Length × log2(Character Pool Size)",
      explanation: "Measures brute-force resistance. 80+ bits is considered highly secure against supercomputing attacks.",
    },
    howItWorks: [
      "Choose your desired password length (8 to 64 characters).",
      "Toggle uppercase, lowercase, numbers, and special symbols.",
      "Optionally exclude ambiguous lookalike characters (0, O, 1, l, I).",
      "Inspect the live entropy rating and copy your secure password.",
    ],
    workedExamples: [
      {
        title: "16-Character High-Entropy Password",
        scenario: "Master vault or financial account security.",
        inputs: { Length: 16, Symbols: true, Numbers: true, Uppercase: true },
        steps: ["Character pool: 94 printable ASCII characters", "Entropy: 16 × log2(94) ≈ 104.9 bits of entropy"],
        result: "k#9X$mQ2!vL7*wP4 (Very Strong)",
      },
    ],
    useCases: [
      "Creating strong master passwords for password managers",
      "Generating secure Wi-Fi pre-shared keys (WPA3)",
      "Database credentials and API secret keys",
    ],
    faq: [
      {
        question: "Is this password generator secure?",
        answer: "Yes. It uses the browser's native Web Cryptography API (crypto.getRandomValues), which gathers hardware entropy. No passwords are ever saved or transmitted across the network.",
      },
    ],
    relatedToolSlugs: [
      "hash-generator",
      "uuid-generator",
      "base64-encoder-decoder",
    ],
  },

  "hash-generator": {
    id: "hash-generator",
    slug: "hash-generator",
    name: "Hash Generator (SHA-256, SHA-512, SHA-1, MD5)",
    category: "technology",
    shortDescription: "Generate cryptographic cryptographic hashes (SHA-256, SHA-512, SHA-1) directly in your browser.",
    description: "Generate one-way cryptographic hash digests from text input using native browser Web Crypto acceleration.",
    title: "Hash Generator – SHA-256, SHA-512 & SHA-1 Online Tool",
    metaDescription: "Generate cryptographic hash digests (SHA-256, SHA-512, SHA-1) online. Fast, secure, and executed 100% client-side.",
    keywords: ["hash generator", "sha256 generator", "sha512 generator", "md5 generator", "hash calculator"],
    iconName: "Hash",
    status: "published",
    seoPriority: 93,
    isPopular: true,
    author: { name: "NexusTools Security Team", role: "Cybersecurity Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "Hash = CryptoSubtle.digest('SHA-256', textBuffer)",
      explanation: "Deterministic one-way mathematical function mapping arbitrary data to a fixed 256-bit or 512-bit hexadecimal string.",
    },
    howItWorks: [
      "Enter your input text into the box.",
      "Select your hashing algorithm (SHA-256, SHA-512, SHA-1).",
      "Copy the calculated hexadecimal checksum.",
    ],
    workedExamples: [
      {
        title: "SHA-256 hash of 'admin'",
        scenario: "Verifying checksum generation.",
        inputs: { Text: "admin", Algorithm: "SHA-256" },
        steps: ["Digest binary bytes", "Output 64-character hexadecimal checksum"],
        result: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
      },
    ],
    useCases: [
      "File and payload integrity verification",
      "HMAC signature preparation and API authentication",
      "Software development and security auditing",
    ],
    faq: [
      {
        question: "Can a SHA-256 hash be reversed back to original text?",
        answer: "No. Cryptographic hash functions are mathematically one-way. You cannot reverse a hash without brute-forcing every possible original input string.",
      },
    ],
    relatedToolSlugs: [
      "password-generator",
      "base64-encoder-decoder",
      "uuid-generator",
    ],
  },

  "word-counter": {
    id: "word-counter",
    slug: "word-counter",
    name: "Word Counter & Text Analyzer",
    category: "text-tools",
    shortDescription: "Count words, characters, sentences, paragraphs, reading time, and keyword density in real-time.",
    description: "Comprehensive writing analytics tool calculating word counts, character counts (with and without spaces), reading time, and keyword frequency.",
    title: "Word Counter – Count Words, Characters & Reading Time",
    metaDescription: "Free online word counter, character counter, sentence counter, estimated reading time, and keyword density analyzer.",
    keywords: ["word counter", "character counter", "count words", "reading time calculator", "word count online"],
    iconName: "Type",
    status: "published",
    seoPriority: 99,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Content Team", role: "Editorial & Content Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      text: "Reading Time = Word Count / 200 WPM | Speaking Time = Word Count / 130 WPM",
      explanation: "Analyzes tokenized word boundaries, sentence terminators, and calculates reading velocity.",
    },
    howItWorks: [
      "Type or paste your text into the editor.",
      "Watch word count, character count, sentence count, and reading time calculate in real time.",
      "Review the keyword frequency table to balance vocabulary and word distribution.",
    ],
    workedExamples: [
      {
        title: "Analyzing a 500-word blog post",
        scenario: "Checking article length and readability.",
        inputs: { Words: 500 },
        steps: ["500 words / 200 WPM = 2.5 minutes reading time", "500 words / 130 WPM = 3.8 minutes speaking time"],
        result: "500 Words | ~2.5 min read",
      },
    ],
    useCases: [
      "Academic essays and university word count limits",
      "Social media post character limits (Twitter/X, Meta, LinkedIn)",
      "Article writing, essay drafts, and keyword frequency checks",
    ],
    faq: [
      {
        question: "What is the standard reading speed for adults?",
        answer: "The average adult reads non-technical English prose at approximately 200 to 250 words per minute (WPM).",
      },
    ],
    relatedToolSlugs: [
      "character-counter",
      "case-converter",
      "text-diff-compare",
      "slug-generator",
    ],
  },

  "character-counter": {
    id: "character-counter",
    slug: "character-counter",
    name: "Character Counter",
    category: "text-tools",
    shortDescription: "Count exact character count with and without spaces for social media, page descriptions, and forms.",
    description: "Check character limits for Twitter (280 chars), Meta descriptions (155 chars), and Google Search titles (60 chars).",
    title: "Character Counter – Count Characters With & Without Spaces",
    metaDescription: "Count characters with and without spaces online. Perfect for Twitter limits, web page descriptions, and character-restricted forms.",
    keywords: ["character counter", "count characters", "letter counter", "character count online", "text length"],
    iconName: "AlignLeft",
    status: "published",
    seoPriority: 94,
    isPopular: true,
    author: { name: "NexusTools Content Team", role: "Editorial & Content Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "Total Characters = text.length | Without Spaces = text.replace(/\\s+/g, '').length",
      explanation: "Computes total UTF-16 code units with and without whitespace characters.",
    },
    howItWorks: [
      "Paste or type your content.",
      "See total characters, characters excluding whitespace, and compatibility indicators for popular social platforms.",
    ],
    workedExamples: [
      {
        title: "Writing a webpage description",
        scenario: "Optimizing for Google Search results.",
        inputs: { Text: "Calculate percentages easily: find X% of Y, what percent X is of Y, or percentage increase/decrease." },
        steps: ["Total character count: 99 characters", "Within recommended 140-160 character range"],
        result: "99 characters (Optimal length)",
      },
    ],
    useCases: [
      "Crafting webpage title tags (under 60 chars) and meta descriptions (under 160 chars)",
      "Ad copy character limit compliance (Google Ads, Facebook Ads)",
      "SMS text message length (160 characters per SMS segment)",
    ],
    faq: [
      {
        question: "Do emojis count as 1 character?",
        answer: "In standard JavaScript character counting, many emojis use surrogate pairs (2 characters) or multi-byte combinations with modifiers.",
      },
    ],
    relatedToolSlugs: [
      "word-counter",
      "case-converter",
      "slug-generator",
    ],
  },

  "case-converter": {
    id: "case-converter",
    slug: "case-converter",
    name: "Case Converter (Title, Camel, Snake, Kebab)",
    category: "text-tools",
    shortDescription: "Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, and kebab-case.",
    description: "Transform text casing instantly for writing, code variables, database column names, and URL slugs.",
    title: "Case Converter – Title Case, camelCase, snake_case & UPPERCASE",
    metaDescription: "Convert text casing online: Title Case, UPPERCASE, lowercase, camelCase, snake_case, PascalCase, and kebab-case instantly.",
    keywords: ["case converter", "title case converter", "camelcase converter", "snake case converter", "uppercase to lowercase"],
    iconName: "CaseSensitive",
    status: "published",
    seoPriority: 93,
    isPopular: true,
    author: { name: "NexusTools Content Team", role: "Software & Editorial Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "Applies regex tokenization and Unicode casing transformations across delimiter boundaries",
      explanation: "Converts strings to various case standards used in literature and programming languages.",
    },
    howItWorks: [
      "Enter your raw text.",
      "Click on your desired case format (e.g. Title Case, UPPERCASE, camelCase, snake_case, kebab-case).",
      "Copy transformed text to clipboard.",
    ],
    workedExamples: [
      {
        title: "Converting 'hello world user profile' to camelCase",
        scenario: "Creating a JavaScript variable name.",
        inputs: { Text: "hello world user profile", Target: "camelCase" },
        steps: ["Split words", "Capitalize subsequent words: hello, World, User, Profile"],
        result: "helloWorldUserProfile",
      },
    ],
    useCases: [
      "Formatting article titles according to Chicago/AP style guides",
      "Refactoring programming variables (camelCase, PascalCase, snake_case)",
      "Creating clean kebab-case URL slugs and file names",
    ],
    faq: [
      {
        question: "What is kebab-case?",
        answer: "kebab-case is a naming convention where words are all lowercase and separated by hyphens (e.g., this-is-kebab-case), widely used in URLs and CSS class names.",
      },
    ],
    relatedToolSlugs: [
      "slug-generator",
      "word-counter",
      "text-diff-compare",
    ],
  },

  "text-diff-compare": {
    id: "text-diff-compare",
    slug: "text-diff-compare",
    name: "Text Diff & Compare Tool",
    category: "text-tools",
    shortDescription: "Compare two text documents or code snippets and highlight additions, deletions, and line changes.",
    description: "Visual diff comparison tool highlighting line-by-line insertions, modifications, and removals with clear color coding.",
    title: "Text Diff Tool – Compare & Find Differences in Text",
    metaDescription: "Compare two text documents or code snippets to find differences, added lines, and removed content. Fast, private online diff tool.",
    keywords: ["text diff", "text compare", "diff checker", "compare text online", "find text differences"],
    iconName: "GitCompare",
    status: "published",
    seoPriority: 91,
    isPopular: true,
    author: { name: "NexusTools Engineering Team", role: "Software Engineering Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-14",
    formula: {
      text: "Line-by-line comparison with insertion/deletion delta markers",
      explanation: "Computes differences between original and modified strings and visualizes added, deleted, and unchanged lines.",
    },
    howItWorks: [
      "Paste your original text in the left pane.",
      "Paste the revised/modified text in the right pane.",
      "Inspect the highlighted differences: green for added text, red for deleted text.",
    ],
    workedExamples: [
      {
        title: "Comparing code configuration files",
        scenario: "Reviewing changes before deployment.",
        inputs: { Original: "port: 3000\nenv: dev", Modified: "port: 8080\nenv: prod" },
        steps: ["Highlight changed line numbers", "Mark substitutions"],
        result: "Clear visual diff highlighting modified port and env values",
      },
    ],
    useCases: [
      "Proofreading revised essays and editorial drafts",
      "Comparing code revisions and configuration files",
      "Detecting contract and legal agreement modifications",
    ],
    faq: [
      {
        question: "Is my compared text stored anywhere?",
        answer: "No. The diff computation is executed entirely within your browser's JavaScript runtime. Nothing is logged or transmitted.",
      },
    ],
    relatedToolSlugs: [
      "word-counter",
      "case-converter",
    ],
  },

  "slug-generator": {
    id: "slug-generator",
    slug: "slug-generator",
    name: "URL Slug Generator & Sanitizer",
    category: "text-tools",
    shortDescription: "Convert article titles and strings into clean, permanent URL slugs.",
    description: "Generate lowercase, hyphen-separated, safe URL slugs with automatic removal of special characters and stop words.",
    title: "Slug Generator – Create Clean & Web Friendly URLs",
    metaDescription: "Generate clean, web-friendly URL slugs from titles and text. Converts special characters and spaces into clean hyphens.",
    keywords: ["slug generator", "url slug generator", "create slug", "clean url creator", "permalink generator"],
    iconName: "Compass",
    status: "published",
    seoPriority: 88,
    author: { name: "NexusTools Content Team", role: "Web Content Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-12",
    formula: {
      text: "Slug = text.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')",
      explanation: "Converts strings to lowercase ASCII, removes accents, and replaces whitespace and symbols with hyphens.",
    },
    howItWorks: [
      "Type or paste your headline or title.",
      "The tool generates a clean, URL-safe slug immediately.",
      "Copy the slug for your CMS or blog post URL.",
    ],
    workedExamples: [
      {
        title: "Generating slug for: 'Top 10 Best Online Calculators & Tools in 2026!'",
        scenario: "Blog post publishing.",
        inputs: { Title: "Top 10 Best Online Calculators & Tools in 2026!" },
        steps: ["Lowercase: 'top 10 best online calculators & tools in 2026!'", "Replace & with 'and'", "Strip punctuation, replace spaces with hyphens"],
        result: "top-10-best-online-calculators-and-tools-in-2026",
      },
    ],
    useCases: [
      "WordPress, Next.js, and headless CMS URL routing",
      "E-commerce product slug standardization",
      "Website content management and clean permalink structure",
    ],
    faq: [
      {
        question: "Why should URL slugs only use hyphens instead of underscores?",
        answer: "Web browsers and search engines treat hyphens as word separators (e.g. 'word-counter' = 'word counter'), making web addresses much easier for people to read and remember.",
      },
    ],
    relatedToolSlugs: [
      "case-converter",
      "url-encoder-decoder",
      "word-counter",
    ],
  },

  "pomodoro-timer": {
    id: "pomodoro-timer",
    slug: "pomodoro-timer",
    name: "Pomodoro Focus Timer & Stopwatch",
    category: "productivity",
    shortDescription: "Customizable 25-minute focus intervals, 5-minute short breaks, and 15-minute long breaks with audio cues.",
    description: "Science-backed productivity timer using the Pomodoro technique to improve focus, prevent mental fatigue, and track study intervals.",
    title: "Pomodoro Timer – Focus Intervals & Break Tracker",
    metaDescription: "Free online Pomodoro timer with customizable 25/5 min focus cycles, audio chime alerts, and stopwatch mode.",
    keywords: ["pomodoro timer", "focus timer", "study timer", "pomodoro technique", "online stopwatch"],
    iconName: "Timer",
    status: "published",
    seoPriority: 95,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Productivity Team", role: "Productivity & Focus Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      text: "1 Pomodoro Cycle = 25 min Focus + 5 min Short Break (Long Break every 4 cycles)",
      explanation: "Time management methodology developed by Francesco Cirillo in the late 1980s.",
    },
    howItWorks: [
      "Click 'Start' to begin your 25-minute uninterrupted work sprint.",
      "When the chime sounds, take a 5-minute short restorative break.",
      "After completing 4 focus sprints, enjoy a 15-minute long break.",
    ],
    workedExamples: [
      {
        title: "Standard 2-Hour Study Session",
        scenario: "Preparing for professional exams.",
        inputs: { Sprints: 4, "Focus Time": "25 min", "Break Time": "5 min" },
        steps: ["Sprint 1 (25m) + Break (5m)", "Sprint 2 (25m) + Break (5m)", "Sprint 3 (25m) + Break (5m)", "Sprint 4 (25m) + Long Break (15m)"],
        result: "100 minutes of deep focus achieved",
      },
    ],
    useCases: [
      "Deep work programming and technical writing sessions",
      "University exam preparation and study blocks",
      "Preventing work burnout and eye strain",
    ],
    faq: [
      {
        question: "Why is the Pomodoro technique so effective?",
        answer: "It breaks daunting tasks into bite-sized 25-minute intervals, reducing procrastination and training your brain to focus without distraction.",
      },
    ],
    relatedToolSlugs: [
      "qr-code-generator",
      "word-counter",
    ],
  },

  "qr-code-generator": {
    id: "qr-code-generator",
    slug: "qr-code-generator",
    name: "QR Code Generator (PNG & SVG)",
    category: "productivity",
    shortDescription: "Generate custom high-resolution QR codes for websites, Wi-Fi networks, text, and contact cards.",
    description: "Create instant vector and high-res PNG QR codes with customizable sizes, colors, and error correction levels.",
    title: "QR Code Generator – Create Custom QR Codes Online",
    metaDescription: "Generate high resolution QR codes for URLs, text, Wi-Fi, and contacts. Free download in PNG format with zero expiration.",
    keywords: ["qr code generator", "create qr code", "free qr code", "qr code maker", "custom qr code"],
    iconName: "QrCode",
    status: "published",
    seoPriority: 97,
    isPopular: true,
    isFeatured: true,
    author: { name: "NexusTools Engineering Team", role: "Software Engineering Editors" },
    reviewer: { name: "Dr. Sarah Jenkins", role: "Computational Mathematician" },
    lastUpdated: "2026-02-15",
    formula: {
      text: "Generates 2D matrix barcode conforming to ISO/IEC 18004 standards with Reed-Solomon error correction",
      explanation: "Encodes binary, alphanumeric, or byte payloads into high-density 2D optical readable matrix patterns.",
    },
    howItWorks: [
      "Enter your target URL, Wi-Fi details, or text.",
      "Select desired size (e.g. 256px, 512px) and error correction level (Low, Medium, High).",
      "Download the QR code image immediately with no watermarks or expiration dates.",
    ],
    workedExamples: [
      {
        title: "Generating QR Code for Website URL",
        scenario: "Printing on business cards and posters.",
        inputs: { URL: "https://nexustools.io" },
        steps: ["Encode URL into QR matrix", "Apply Reed-Solomon error correction", "Render to canvas"],
        result: "Crisp, scannable QR code ready to download",
      },
    ],
    useCases: [
      "Restaurant menus and contactless ordering links",
      "Business cards and promotional marketing flyers",
      "Guest Wi-Fi network instant connection cards",
    ],
    faq: [
      {
        question: "Do these generated QR codes ever expire?",
        answer: "No. These are static QR codes that encode your exact destination directly into the barcode pattern. They never expire and work permanently.",
      },
    ],
    relatedToolSlugs: [
      "pomodoro-timer",
      "url-encoder-decoder",
      "uuid-generator",
    ],
  },
};

export const TOOL_LIST = Object.values(TOOLS);

export function getToolBySlug(slug: string): ToolItem | undefined {
  return TOOLS[slug];
}

export function getToolsByCategory(category: string): ToolItem[] {
  return TOOL_LIST.filter((t) => t.category === category);
}

export function getPopularTools(): ToolItem[] {
  return TOOL_LIST.filter((t) => t.isPopular);
}

export function getFeaturedTools(): ToolItem[] {
  return TOOL_LIST.filter((t) => t.isFeatured);
}
